{
  "name": "with-error",
  "version": "0.0.1",
  "description": "Exception as function",
  "main": "index.js",
  "scripts": {
    "test": "tsc && tslint --project tsconfig.json && jest --verbose --coverage && treest",
    "watch:test": "jest --watch --coverage --verbose"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/arvitaly/with-error.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/arvitaly/with-error/issues"
  },
  "homepage": "https://github.com/arvitaly/with-error#readme",
  "jest": {},
  "devDependencies": {
    "@types/jest": "^22.2.2",
    "coveralls": "^3.0.0",
    "jest": "^22.4.3",
    "treest": "^0.0.6",
    "tslint": "^5.9.1",
    "typescript": "^2.8.1"
  }
}
